services:
  - type: web
    name: linktree-app
    env: docker
    repo: https://github.com/your-username/your-repo
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.qmmlaslpfdcezryrgges:NgocSinh2311@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
