"""Delete user_id to Subcategory table

Revision ID: 17ced3ac220b
Revises: f42dd27024ee
Create Date: 2025-08-06 12:29:44.610763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ced3ac220b'
down_revision = 'f42dd27024ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subcategory_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('subcategory_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
